In [32]:
import numpy as np
import cv2

In [23]:
img = cv2.imread("Ritesh.jpg",1)
print(img)

[[[  0   2   3]
  [  1   3   4]
  [  0   2   3]
  ...
  [  1   3   4]
  [  0   2   3]
  [  0   2   3]]

 [[  0   2   3]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   1]
  [  0   2   3]
  [  0   2   3]]

 [[  6   6   6]
  [ 45  45  45]
  [ 51  51  51]
  ...
  [ 45  44  46]
  [  8   7   9]
  [  0   1   2]]

 ...

 [[ 16   9   6]
  [141  53  17]
  [155  57  15]
  ...
  [112  31   4]
  [ 18   5   3]
  [  0   0   5]]

 [[  1   3   4]
  [ 27  11   5]
  [ 27  11   5]
  ...
  [ 20   4   5]
  [  1   3   4]
  [  0   1   5]]

 [[  0   2   3]
  [  1   0   2]
  [  0   1   2]
  ...
  [  0   1   2]
  [  1   3   4]
  [  0   2   2]]]


In [18]:

resized = cv2.resize(img,(600*2,int(400/2)))
cv2.imshow("Capture",resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [57]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml') 
  

# Trained XML file for detecting eyes 
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')  
  
# capture frames from a camera 
cap = cv2.VideoCapture(0) 
cap.set(10,5000)
  
# loop runs if capturing has been initialized. 
while 1:  
  
    # reads frames from a camera 
    ret, img = cap.read()  
  
    # convert to gray scale of each frames 
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
  
    # Detects faces of different sizes in the input image 
    faces = face_cascade.detectMultiScale(gray, 1.3, 5) 
  
    for (x,y,w,h) in faces: 
        # To draw a rectangle in a face  
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,172,40),2)  
        roi_gray = gray[y:y+h, x:x+w] 
        roi_color = img[y:y+h, x:x+w] 
  
        # Detects eyes of different sizes in the input image 
        eyes = eye_cascade.detectMultiScale(roi_gray)  
  
        #To draw a rectangle in eyes 
        for (ex,ey,ew,eh) in eyes: 
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,127,255),2) 
  
    # Display an image in a window 
    cv2.imshow('img',img) 
  
    # Wait for Esc key to stop 
    k = cv2.waitKey(1) & 0xff
    if k == 27: 
        break
  
# Close the window 
cap.release() 
  
# De-allocate any associated memory usage 
cv2.destroyAllWindows()  